@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Nov 25 22:29:18 +0100 2025
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim VGA_testbench_behav -key {Behavioral:sim_1:Functional:VGA_testbench} -tclbatch VGA_testbench.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/abonn/Desktop/Cours_ESIREM/5eme_Annee/interface_systemes_embarques/TP/TP_video_VGA_2019/VGA_testbench_behav.wcfg -log simulate.log"
call xsim  VGA_testbench_behav -key {Behavioral:sim_1:Functional:VGA_testbench} -tclbatch VGA_testbench.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/abonn/Desktop/Cours_ESIREM/5eme_Annee/interface_systemes_embarques/TP/TP_video_VGA_2019/VGA_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
